# .travis.yml
language: ruby

bundler_args: --without production development

rvm:
  - 1.9.3

env:
  - DB=mysql
  #- DB=postgresql

script: bundle exec rake spec

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:drop db:create db:schema:load --trace 2>&1
  #- mysql -e 'create database web6ey_test'
  #- psql -c 'create database web6ey_test' -U postgres
