# .travis.yml
language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
  #- DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database web6ey_test'
  #- psql -c 'create database web6ey_test' -U postgres